name: Daily ClamAV Version Refresh

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily_refresh:
    name: Refresh ClamAV definitions
    runs-on: runs-on
    env:
      GITHUB_TOKEN: ${{ secrets.CITIZENSADVICE_CLAMAV_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - name: Refresh ClamAV version
        run: echo $(dig +short current.cvd.clamav.net txt | tr -d '"') > current.cvd.clamav.net.txt

      - name: Print diff
        run: |
          git diff current.cvd.clamav.net.txt

      - name: Add, Commit & Push changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: "Citizens Advice GitHub Action"
          author_email: "83002696+citizensadvice-clamav@users.noreply.github.com"
          message: "Daily rebuild - update ClamAV definitions"
          add: "current.cvd.clamav.net.txt"
          push: true

  docker_build:
    name: Build and Push Docker Image
    needs: daily_refresh
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
